
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: khacnhat/web-dojo
    init: true
    container_name: test-web
    volumes:
      - ./test:/cyber-dojo/test:ro
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - starter
      - runner
      - saver
      - differ
      - mapper
      - zipper

  # - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: khacnhat/starter-dojo
    init: true
    container_name: test-web-starter
    ports:
      - 4527:4527
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./test/data/start_points:/app/start_points:ro

  # - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: khacnhat/runner-dojo
    init: true
    container_name: test-web-runner
    read_only: true
    ports:
      - 4597:4597
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: khacnhat/saver-dojo
    init: true
    container_name: test-web-saver
    read_only: true
    ports:
      - 4537:4537
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - mapper
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  # - - - - - - - - - - - - - - - -

  mapper:
    user: nobody
    image: khacnhat/mapper-dojo
    init: true
    container_name: test-web-mapper
    read_only: true
    ports:
      - 4547:4547
    tmpfs: /tmp
    restart: 'no'
    tmpfs:
      - /tmp:uid=65534,gid=65533
    volumes:
      - ./test/data/porter:/porter:ro

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: khacnhat/differ-dojo
    init: true
    container_name: test-web-differ
    read_only: true
    ports:
      - 4567:4567
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: khacnhat/zipper-dojo
    init: true
    container_name: test-web-zipper
    read_only: true
    ports:
      - 4587:4587
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - saver
